In [ ]:
import pandas as pd
import numpy as np
 
# Varianta 5
data = {
    "wire_lengths": [5670, 8912],
    "client_amount": [120, 310],
    "total_costs": [45000, 78000]
}
df = pd.DataFrame(data)
df.to_csv("centre_regionale.csv", index=False)
 
# Pasul 2.2 — încărcarea datelor din fișierul CSV
df = pd.read_csv("centre_regionale.csv")
 
# Pasul 2.3 — extragerea vectorilor
wire_lengths = df["wire_lengths"].to_numpy()
client_amounts = df["client_amount"].to_numpy()

total_costs = df["total_costs"].to_numpy()
 
print("Vectorul lungimilor de cablu:", wire_lengths)
print("Vectorul numărului de clienți:", client_amounts)
print("Vectorul costurilor totale:", total_costs)

print()
print("Rezolvam ecuatia de tip: Ax = B <=> x = A^(-1) * B")
print()

A = np.matrix([wire_lengths, client_amounts]).T
print("Matricea A:")
print(A)
print()

print("Vectorul B:")
print(total_costs)
print()

invA = A.getI()
print("Matricea inversa A^(-1):")
print(invA)
print()

x = np.matmul(invA, total_costs)
print("Rezultatul ecuatiei (x):", x)



Vectorul lungimilor de cablu: [5670 8912]
Vectorul numărului de clienți: [120 310]
Vectorul costurilor totale: [45000 78000]

Rezolvam ecuatia de tip: Ax = B <=> x = A^(-1) * B

Matricea A:
[[5670  120]
 [8912  310]]

Vectorul B:
[45000 78000]

Matricea inversa A^(-1):
[[ 0.00045041 -0.00017435]
 [-0.0129486   0.00823817]]

Rezultatul ecuatiei (x): [[ 6.66899137 59.89015779]]


In [ ]:

# Varianta 14 — compania de construcții

import pandas as pd
import numpy as np

data = {
    "ciment": [2, 3, 1],
    "nisip": [3, 1, 4],
    "otel_beton": [1, 2, 3],
    "total_costs": [4800, 5200, 6100]
}

df = pd.DataFrame(data)
print("Datele introduse:")
print(df)
print()

ciment = df["ciment"].to_numpy()
nisip = df["nisip"].to_numpy()
otel_beton = df["otel_beton"].to_numpy()
total_costs = df["total_costs"].to_numpy()

print("Cantitatea cimentului:", ciment)
print("Cantitatea nisipului:", nisip)
print("Cantitatea oțel-betonului:", otel_beton)
print("Costul total:", total_costs)

print()
print("Rezolvam ecuatia de tip: Ax = B <=> x = A^(-1) * B")
print()

A = np.matrix([ciment, nisip, otel_beton]).T

print("Matricea A:")
print(A)
print()

print("Vectorul B:")
print(total_costs)
print()

invA = A.getI()
print("Matricea inversa A^(-1):")
print(invA)
print()

x = np.matmul(invA, total_costs)
print("Rezultatul ecuatiei (x):", x)



Datele introduse:
   ciment  nisip  otel_beton  total_costs
0       2      3           1         4800
1       3      1           2         5200
2       1      4           3         6100

Cantitatea cimentului: [2 3 1]
Cantitatea nisipului: [3 1 4]
Cantitatea oțel-betonului: [1 2 3]
Costul total: [4800 5200 6100]

Rezolvam ecuatia de tip: Ax = B <=> x = A^(-1) * B

Matricea A:
[[2 3 1]
 [3 1 2]
 [1 4 3]]

Vectorul B:
[4800 5200 6100]

Matricea inversa A^(-1):
[[ 0.25  0.25 -0.25]
 [ 0.35 -0.25  0.05]
 [-0.55  0.25  0.35]]

Rezultatul ecuatiei (x): [[975. 685. 795.]]


In [18]:
# VarIAnta 28 — companIA IT
import pandas as pd
import numpy as np

data = {
    "develop": [0.70, 0.15],
    "infra":   [0.20, 0.60],
    "demand":  [80, 50]
}

df = pd.DataFrame(data)
print("Datele introduse:")
print(df)
print()

develop = df["develop"].to_numpy()
infra   = df["infra"].to_numpy()
demand  = df["demand"].to_numpy()

print("Coeficienții pentru dezvoltare:", develop)
print("Coeficienții pentru infrastructură:", infra)
print("Cererea finală:", demand)

print()
print("Rezolvam ecuatIA de tip: x = (I-A)^-1 * d")
print()

A = np.matrix([develop, infra]).T
print("Matricea A:")
print(A)
print()

I = np.eye(2)

IA = I - A
print("Matricea (I - A):")
print(IA)
print()

invIA = IA.getI()
print("Matricea inversa (I - A)^(-1):")
print(invIA)
print()

x = invIA @ demand
print("Volumul total de activitate necesar pentru fiecare divizie:", x)


Datele introduse:
   develop  infra  demand
0     0.70    0.2      80
1     0.15    0.6      50

Coeficienții pentru dezvoltare: [0.7  0.15]
Coeficienții pentru infrastructură: [0.2 0.6]
Cererea finală: [80 50]

Rezolvam ecuatIA de tip: x = (I-A)^-1 * d

Matricea A:
[[0.7  0.2 ]
 [0.15 0.6 ]]

Matricea (I - A):
[[ 0.3  -0.2 ]
 [-0.15  0.4 ]]

Matricea inversa (I - A)^(-1):
[[4.44444444 2.22222222]
 [1.66666667 3.33333333]]

Volumul total de activitate necesar pentru fiecare divizie: [[466.66666667 300.        ]]
